name: Docker Image CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag alexnederlof/tradfri-mqtt
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor # includes patch updates!
          github-token: ${{ secrets.mytoken }}
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor # includes patch updates!
          github-token: ${{ secrets.mytoken }}
